IrodsHost:
IrodsPort:
IrodsZone:
IrodsAdminUser:
IrodsAdminPassword:
IrodsAdminPasswordFile:
IrodsAuthScheme:
IrodsNegotiationPolicy:
IrodsDefaultResource:

IrodsPrimaryTestUser: test1
IrodsPrimaryTestPassword: test
IrodsSecondaryTestUser: test2
IrodsSecondaryTestPassword: test
