IrodsHost:
IrodsPort:
IrodsZone:
IrodsAdminUser:
IrodsAdminPassword:
IrodsAdminPasswordFile:
IrodsAdminLoginType:
IrodsAuthScheme:
IrodsNegotiationPolicy: native
IrodsDefaultResource:

IrodsPrimaryTestUser: test1
IrodsPrimaryTestPassword: test
IrodsSecondaryTestUser: test2
IrodsSecondaryTestPassword: test2
